version: '3'

services:
    app:
        build:
            context: .
        ports:
            - "8080:9000"
        volumes:
            - .:/var/www/html

    db:
        image: debian:bullseye-slim
        volumes:
            - ./database:/var/lib/sqlite
